def unnamed():
  set_tool_voltage(0)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(2.0)
  set_safety_mode_transition_hardness(1)
  set_gravity([0.0, 0.0, 9.82])
  step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f = 0.0
  thread Step_Counter_Thread_94b40e7e_a4f1_4b6b_94f4_c6bf4a42c8fd():
    while (True):
      step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f = step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_94b40e7e_a4f1_4b6b_94f4_c6bf4a42c8fd()
  while (True):
    $ 1 "Robot Program"
    $ 2 "Script: programa3.script"
      set_gravity([0.0, 0.0, 9.82])
      set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
      set_payload(2.0)
      set_tool_voltage(0)
      global v = 0.2
      global a = 0.5
    
      while (True):
        popup("Iniciando rutina Pick and Place", "Programa 3", False, False, True)
    
        movej(p[0.300, 0.000, 0.300, 3.14, 0.0, 0.0], a, v)
    
        movej(p[0.250, -0.100, 0.300, 3.14, 0.0, 0.0], a, v)
        movej(p[0.250, -0.100, 0.150, 3.14, 0.0, 0.0], a, v)
        set_digital_out(0, True)
        sleep(0.5)
        movej(p[0.250, -0.100, 0.250, 3.14, 0.0, 0.0], a, v)
        movej(p[0.350, 0.100, 0.250, 3.14, 0.0, 0.0], a, v)
        movej(p[0.350, 0.100, 0.150, 3.14, 0.0, 0.0], a, v)
        set_digital_out(0, False)
        sleep(0.5)
        movej(p[0.350, 0.100, 0.250, 3.14, 0.0, 0.0], a, v)
    
        movej(p[0.400, -0.100, 0.300, 3.14, 0.0, 0.0], a, v)
        movej(p[0.400, -0.100, 0.150, 3.14, 0.0, 0.0], a, v)
        set_digital_out(0, True)
        sleep(0.5)
        movej(p[0.400, -0.100, 0.250, 3.14, 0.0, 0.0], a, v)
        movej(p[0.450, 0.100, 0.250, 3.14, 0.0, 0.0], a, v)
        movej(p[0.450, 0.100, 0.150, 3.14, 0.0, 0.0], a, v)
        set_digital_out(0, False)
        sleep(0.5)
        movej(p[0.450, 0.100, 0.250, 3.14, 0.0, 0.0], a, v)
    
        movej(p[0.300, 0.000, 0.300, 3.14, 0.0, 0.0], a, v)
    
        popup("Rutina completada. Active entrada digital DI[0] para reiniciar.", "Esperando confirmación", False, False, True)
        while (not get_digital_in(0)):
          sleep(0.1)
        end
      end
  end
end
