def program2():
  set_tool_voltage(0)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(2.0)
  set_safety_mode_transition_hardness(1)
  set_gravity([0.0, 0.0, 9.82])
  step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f = 0.0
  thread Step_Counter_Thread_94b40e7e_a4f1_4b6b_94f4_c6bf4a42c8fd():
    while (True):
      step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f = step_count_8e476995_aeaf_42c9_b874_ddf4e6764e3f + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_94b40e7e_a4f1_4b6b_94f4_c6bf4a42c8fd()
  while (True):
    $ 1 "Robot Program"
    $ 2 "Script: programa2.script"
      set_gravity([0.0, 0.0, 9.82])
      set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
      set_payload(2.0)
      set_tool_voltage(0)
    
      set_digital_out(0, True)
    
      popup("El control va a ser compartido con un controlador externo. Presione OK.", "Aviso", False, False, True)
    
      sleep(5.0)
    
      popup("Control compartido con ROS2. El robot está bajo control externo.", "Aviso", False, False, False)
    
      # Mantener el robot activo para recibir comandos externos
      while (True):
        sleep(0.1)
      end
  end
end
